import Promptinput from "@/components/Promptinput";
import Header from "../components/Header";

import '../styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Header />
       <Promptinput/>
        {children}
      
      
      
      </body>
    </html>
  )
}
